### PR TITLE
Data Patch Pipeline and Patch 001

### PR DESCRIPTION
**Pull request by jikac**
This pull request incorporates a data patching methodology and a restructuring of the data folder. It also removes unused files and reorganizes things.

The web book builds great on my local machine and all figures and numbers work as expected.

In this PR is a data patch as well `data/patches/patch_001` that adds the missing Southcentral Power Project data from 2013-2020.

### CODE REVIEW

**Comment by eldobbins** [comment]
What is the relationship between `data/main.R` and `scripts/main.R`?

**Comment by jikac** [comment]
> What is the relationship between `data/main.R` and `scripts/main.R`?

`data/main.R` is a modern implementation of `scripts/main.R`. If we can confirm that the `scripts` directory has no dependencies, we might consider removing it.

**Comment by eldobbins** [comment]
OK. I don't think that needs to stand in the way of this PR.  I will make an issue to clarify this in the future.
And thinking about it, it may make more sense to have the patches scripts in `scripts/` but since the names of `main.R` conflict, that won't be possible until `scripts/` is cleaned up.

(The justification for separating scripts and data is that scripts can be tracked in GitHub, but data really shouldn't. If they are separate, then `data/` can be listed in `.gitignore` while `scripts/` is tracked normally. Not really an issue with our tiny dataset - thinking of the future.)

#70

**Comment by eldobbins** [comment]
@ianalexmac this PR is OK with me (with the addition of the new issue) but I'm leaving approval to you because you are more familiar with the workflow.

**Comment by jikac** [comment]
@ianalexmac @eldobbins actually, the inline functions used to generate statistics are kept in `scripts/inline_functions` so there may be a case to maintain that or move it as well. Something to note, and I'll also add this note to the issue.

**Review by ianalexmac — APPROVED** [review]
Great work Jesse! Thank you.

**Pull request merged**
