### PR TITLE
Transform website to a book

### LINKED ISSUE #44: Convert from website to book
> HTML books are actually just a special type of [Quarto Website](https://quarto.org/docs/websites/) and consequently support all of the same features as websites including full-text search. The most important difference is that HTML books use chapter numbers and therefore support [Cross References](https://quarto.org/docs/authoring/cross-references.html) between different chapters.

Issue arose because figure numbers repeat across the different pages.

Recommend forking project to personal repo where can verify the render works before merging changes because this is a big'n.  https://quarto.org/docs/books/ says how.

### PR DESCRIPTION
**Pull request by eldobbins**
Fixes #44 

This PR makes these changes:
- changes the content of `_quarto.yml` to the book syntax. (The original website code is stashed in a separate backup file.
- adds section cross references and uses those instead of HTML links
- adds table cross references. Note: doing this for the historic reports table wouldn't work with the `insert` set-up so I copied the table into `historic_reports.qmd`
- Change some header levels so they would not get section numbers appended. Book looked "too busy" otherwise
- Changed the figure margins to eliminate excessive space around the tables. I did experiment with centering figures and made notes in #42. Spoiler: I could not center figures generated by Observable.

### CODE REVIEW

**Comment by jikac** [comment]
This looks phenomenal. My only request would be to change the following section titles:
- Alaska Generation Capacity -> Installed Capacity
- Alaska Electricity Generation -> Net/Gross Generation
- Electricity Consumption -> Consumption and Sales

**Comment by ianalexmac** [comment]
Great work! We've heard from a number of researchers who would like straightforward access to the data. Perhaps we could move the "Data Portal" link in the sidebar down to the bottom of the sidebar so it pops a little more?

**Review by jikac — APPROVED** [review]
This looks good. I'm seeing consistent figure labeling, a renaming of section titles, and a reordering of the data portal to be more prominent.

**Review by ianalexmac — COMMENTED** [review]
Looks great!

**Pull request merged**
